### ISSUE TITLE
Model Loader

### ISSUE THREAD

**Issue by slimsag** [azul3d/oldissues#12]
Azul3D will need a model loader to load animated/static 3D models and scenes. Ideally the file format would be targeted towards specifically Azul3D and would have two components, a JSON format for readability and for compatibility with other languages, and a Binary (GOB) format for quick loading into the engine.

Additionally, we will need a Blender Exporter script so that we can bring models and entire scenes from Blender straight into Azul3D.

Exporters would export just to JSON, and then a tool would be made available that allows converting from the (slow, large file size) JSON format into the (fast, small file size) Binary format.

**Comment by shurcooL** [comment]
Ok, just want to give an update on the Collada loader.

I was able to use it successfully to load .dae files exported from SketchUp and render them (in a very rudimentary way for now).

See https://github.com/shurcooL/play/commit/bb12dd54f9d6b69523b695420b4cac9423bddd03#commitcomment-9134222.

(As a side note, I used `assimp` to convert the original source .x model file into .dae. However, since I'm porting a small game with a single 3D model and not building a full-fledged game engine, this basic approach sufficed for me for now. But I can see the usefulness of using libassimp as a general importer of many 3D formats.)

If @GlenKelley doesn't mind, I'd like to add github.com/GlenKelley/go-collada to the awesome-go list of libraries, because as far as I know it is the only working Collada library for Go. I'm willing to help maintain and develop it further.

**Comment by james147** [comment]
You might want to look at http://msgpack.org/ very similar to json, but in a binary format instead so it is much smaller and faster.

As for compressions lzop or lz4 are very good for speed, which will help allot with loading times and also help to reduce disk space, although not as much as slower codecs like gzip.

**Comment by slimsag** [comment]
@james147 I appreciate the well-thought insight. I will look into those and consider them quite seriously.

**Comment by xagaba** [comment]
Are you aware of http://opengex.org/ ?

**Comment by slimsag** [comment]
@xagaba I am, yes. OpenGEX is not a good choice for a run-time format. It is a format for exchange between applications (hence the name `Open Game Engine Exchange Format`), and also by this phrase on the top of their website:

> The Open Game Engine Exchange (OpenGEX) format is a text-based file format designed to facilitate the transfer of complex scene data between applications such as modeling tools and game engines.

For an exchange format, it also lacks a substantial amount of feature preservation when compared to Collada.

**Comment by Seb-C** [comment]
Some time ago I wrote a function to load an `obj` model for WebGL. I would like to translate it for azul3d, and share it here if it's OK.

Should I put it as a function in `gfxutils` ?

**Comment by slimsag** [comment]
This issue was moved to azul3d/engine#18
